### ISSUE TITLE
how to prevent child components expanding beyond parent column?

### ISSUE THREAD

**Issue by AYEG** [ChilliCream/react-rasta#47] opened 2018-11-14 19:45 UTC
Hi! 
I really enjoy the relative simplicity of react-rasta. 

Right now I'm trying to understand what I can use to prevent children/react components inside a column from expanding everything. I've not seen any difference using Flex="none". 

What approach to take here? 
Is there a flexbox property I need to look into or should I try to use a combination of css via styled components on those child components?

**Comment by rstaib** [comment] 2018-11-14 20:44
Hi @AYEG,

There is an example for that in the storybook. Unfortunately, I had no time to put those stories on the website so far.

However, If clone the repository and run the following commands, you can see how the flex property changes the behavior of columns.

1) Run `yarn` to install the dependencies.
2) Run `yarn storybook` to start the storybook website.

After starting the storybook, open `http://localhost:6006` in your favorite browser and navigate to `ColumnFlex\flex`. When resizing your browser window from very small to very large you will see what happens.

If you have still questions or need help to find a solution, don't hesitate to get back to me.

**Comment by AYEG** [comment] 2018-11-14 21:16
Thank you @rstaib , 
Unfortunately I'm getting this error when I start storybook:
_**ERROR in [at-loader] ./node_modules/@types/react/index.d.ts:2234:19 
    TS2320: Interface 'Element' cannot simultaneously extend types 'ReactElement<any>' and 'ReactElement<any>'. Named property 'type' of types 'ReactElement<any>' and 'ReactElement<any>' are not identical.**_

![screen shot 2018-11-14 at 10 14 01 pm](https://user-images.githubusercontent.com/5505017/48512855-bd929100-e85a-11e8-9320-82bd586defeb.png)

**Comment by rstaib** [comment] 2018-11-15 17:51
I didn't know why it does not work on your machine. Because I tested the storybook yesterday on different machines with a fresh repository. I even tested it with `npm` and `yarn`. Unfortunately I couldn't reproduce the error shown in your screenshot.

Anyway, I posted the `Column Flexibility` example on [react-rasta.com](https://react-rasta.com/docs/example-column-flex). For the resize test you can directly go [here](https://6vr8k091zr.codesandbox.io/column/flex).

I hope this is going to help you understand how the `Column Flexibility` is working. I will close this issue  for now.

**Closed by rstaib** 2018-11-15 17:51 UTC
Labels: question

**Comment by AYEG** [comment] 2018-11-15 19:23
Really appreciate your help and providing an additional example and no worries about the storybook, I'm not using that anyway. 

So after taking a break from this problem and coming back, I realized the component inside the layout is draw with canvas/WebGL and that this probably is beyond the scope of css which is causing the issues.

**Comment by AYEG** [comment] 2018-11-15 20:19
Yup it's working great now! Fixed it with the dimensions I got from the react-sizeme module :)
Note: I put the sizeme ref on a plain old div (with the canvas element inside) with full-width and height styling that was located inside a parent ReactRasta Column
